module GreenButtonData
  module Enumerations
    TIME_ATTRIBUTE = {
       0 => :none,
       1 => :ten_minute,
       2 => :fifteen_minute,
       3 => :one_minute,
       4 => :twenty_four_hour,
       5 => :thirty_minute,
       6 => :five_minute,
       7 => :sixty_minute,
      10 => :two_minute,
      14 => :three_minute,
      15 => :present,
      16 => :previous,
      31 => :twenty_minute,
      50 => :fixed_block_60_min,
      51 => :fixed_block_30_min,
      52 => :fixed_block_20_min,
      53 => :fixed_block_15_min,
      54 => :fixed_block_10_min,
      55 => :fixed_block_5_min,
      56 => :fixed_block_1_min,
      57 => :rolling_block_60_min_interval_30_min_sub_interval,
      58 => :rolling_block_60_min_interval_20_min_sub_interval,
      59 => :rolling_block_60_min_interval_15_min_sub_interval,
      60 => :rolling_block_60_min_interval_12_min_sub_interval,
      61 => :rolling_block_60_min_interval_10_min_sub_interval,
      62 => :rolling_block_60_min_interval_6_min_sub_interval,
      63 => :rolling_block_60_min_interval_5_min_sub_interval,
      64 => :rolling_block_60_min_interval_4_min_sub_interval,
      65 => :rolling_block_30_min_interval_15_min_sub_interval,
      66 => :rolling_block_30_min_interval_10_min_sub_interval,
      67 => :rolling_block_30_min_interval_6_min_sub_interval,
      68 => :rolling_block_30_min_interval_5_min_sub_interval,
      69 => :rolling_block_30_min_interval_3_min_sub_interval,
      70 => :rolling_block_30_min_interval_2_min_sub_interval,
      71 => :rolling_block_15_min_interval_5_min_sub_interval,
      72 => :rolling_block_15_min_interval_3_min_sub_interval,
      73 => :rolling_block_15_min_interval_1_min_sub_interval,
      74 => :rolling_block_10_min_interval_5_min_sub_interval,
      75 => :rolling_block_10_min_interval_2_min_sub_interval,
      76 => :rolling_block_10_min_interval_1_min_sub_interval,
      77 => :rolling_block_5_min_interval_1_min_sub_interval
    }
  end
end
